### ISSUE TITLE
Level 17 doesn't work?

### ISSUE THREAD

**Issue by ChrisKissoon** [flukeout/css-diner#106]
I have to select small apple small pickle with last-child selector 
When i write the selector:
 .table pickle,plate apple:last-child
The small apple and small pickle shimmies but the level is not completed please tell me where i'm going wrong
![shimmy](https://cloud.githubusercontent.com/assets/13861967/9347700/8923a0c8-4603-11e5-88e4-c1b2e20f7e91.PNG)

**Comment by vihanga-liyanage** [comment]
Actually I think it's a bad example. Even though it's about <strong>:last-child</strong> selector, you could pass by just entering <strong>apple, pickle</strong>

**Comment by jk3us** [comment]
I came up with `plate#fancy :last-child, .table > :last-child`.  It doesn't count it as right, but it shakes the right things :)

I wonder if the [brace/parenthesis mismatch](https://github.com/flukeout/restaurant/blob/master/levels.js#L232) is causing problems:

    board: "{a)()(oO)p"

**Comment by kingIZZZY** [comment]
+1 confusing and wrong to the newbie interns, please fix!

**Comment by flukeout** [comment]
So in general, I'd like to discourage people form using commas between selectors, and will update the diner to block those attempts - I've added that issue to the roadmap. I think maybe I'll save one special level for showing off the comma between rules syntax, but if the comma is allowed, most of the levels can be solved without using the selector that the level is about.

The rule I intended to solve this level is `.small:last-child` - does that help?

Thank you for filing and your thoughts!

**Comment by Teacher-Han-Long** [comment]
Someone posted plate + pickle, which doesn't work, and shouldn't as far as I can see. Anyone else see this?  Also, is it not possible to use examples that actually NEED to use what the lesson is about?

**Comment by FmC00** [comment]
--->    #fancy apple:first-child, .small:last-child   <-----

**Comment by Owczarkov** [comment]
It actually suppose to be:

apple:first-child, pickle:last-child

**Comment by Abhishek-Dinesan** [comment]
.small:last-child

**Comment by SATYAM6560** [comment]
@flukeout .small: last-child is not working in 17 level

**Comment by godekina** [comment]
> .small:last-child

Hi, thanks for the awesome game, it has helped me understand selectors a lot better. As per the solution, wouldn't using the "small" class also select the orange? meanwhile the challenge was to select the apple and pickle. just curious. thanks!

**Comment by lupereda** [comment]
pickle,plate apple: only-child   worked

**Comment by BaffledDevelopment** [comment]
.small: last-child will not work in level 17
 .small :last-child will not work in level 17
 
  .small:last-child works. <------ No space

**Comment by xroy-destroy** [comment]
> > .small:last-child
> 
> Hi, thanks for the awesome game, it has helped me understand selectors a lot better. As per the solution, wouldn't using the "small" class also select the orange? meanwhile the challenge was to select the apple and pickle. just curious. thanks!

That small orange is actually the first, not last, child and so the solution provided by flukeout will not select it. I wondered the same thing.

**Comment by LoukHich** [comment]
:last-child:not(orange)

**Comment by hubert22143** [comment]
Your application has a few bugs, and as a beginner who is just starting to learn, I wouldn't personally recommend your site for newcomers. It tends to create more confusion than its intended value. However, I do acknowledge the significance of exploring every level for the valuable tips provided in the help column, where various selector usages are demonstrated. These insights prove quite useful at times, although I found them a bit perplexing in the context of Level 17 due to a misleading example.

The primary issue stems from the restricted selection of available choices. Despite having the correct answer, it does not allow progression.

Numerous users have reported issues, and I would like to add mine to the list. Specifically, in Level 18:

The selector "div.table > plate:nth-child(3)" does not grant passage, despite its correctness.
However, "plate:nth-child(3)" does lead to successful completion.

I want to express gratitude for the effort you've invested in creating this platform. Although it is quite bewildering and can be frustrating due to the constraints imposed on possible solutions, it has significantly contributed to my learning process. Thank you for that.

**Comment by uicdennis** [comment]
plate :only-child, pickle
This works.

**Comment by Mateyw** [comment]
> > .small:last-child
> 
> Hi, thanks for the awesome game, it has helped me understand selectors a lot better. As per the solution, wouldn't using the "small" class also select the orange? meanwhile the challenge was to select the apple and pickle. just curious. thanks!

No, because there are two oranges in plate where the first element (which is the first-child) is the one with class "small" and the second orange (which is the last-child) doesnt have the class.
