### ISSUE TITLE
:nth-last-child(*) requires many returns

### ISSUE THREAD

**Issue by kaichanvong** [flukeout/css-diner#55]
Example of issue here - http://instagram.com/p/l9UuMyCzwJ/

Could be a browser bug perhaps? Did not investigate this much! Found on Chrome Version 33.0.1750.152

**Comment by ironsidez** [comment]
The reason this is happening is because the answer you are using (while it is correct) isn't the only possible answer and isn't the answer the creator used. In levels.js the selector is written as "bento:nth-last-child(4)" which also selects the same element. I am not sure why spamming it eventually makes it work however.

I have noticed this same issue on several different questions, for example on question 17 to select the .small last children, ".table .small:last-child" or "div.table .small:last-child" would select them as well, but the answer expected is ".small:last-child".  Spamming enter eventually makes it force finish the level anyway though.
