### ISSUE TITLE
Level 18: div.table plate:nth-child(3) does not work

### ISSUE THREAD

**Issue by letalvoj** [flukeout/css-diner#81]
When I type:

"div.table plate:nth-child(3)"

the appropriate plate shakes, but it does not fly off the table! But if i press the enter fast multiple times it suddenly does work :)

**Comment by kingIZZZY** [comment]
+1 please fix, and +1 thanks for the workaround - it works!

**Comment by flukeout** [comment]
The reason for this is that there is a bug that stops the selector from working if `.table` is included in the selector. All of the selectors are already being applied within the `.table` - which is why this is breaking. I've made a note to address this and it's reflected in the roadmap on the README.md, so I'm closing this issue.

So, for now, just don't ever include `div.table` or `.table` in your selectors.

**Comment by Justwatchme007** [comment]
plate:nth-child(3) 

Worked
